kind = "web"
previewPath = "/"
title = "Sepiring"
version = "1.0.0"
id = "artifacts/sepiring"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24781

[services.development]
run = "pnpm --filter @workspace/sepiring run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sepiring", "run", "build" ]
publicDir = "artifacts/sepiring/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24781"
BASE_PATH = "/"
